# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BudgieSaver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BudgieSaver
  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  # [OPTIONAL PODS]
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'BudgieSaverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BudgieSaver-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BudgieSaver-tvOS

  target 'BudgieSaver-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
